title: "Marcelo Borges"
description: "Data & AI | Databases | Go-to-Market Leader in LATAM"
theme: minima

author: "Marcelo Borges"

header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md
