title: "Marcelo Borges"
description: "Data & AI | Databases | Go-to-Market Leader in LATAM"
theme: minima

# Optional config
author:
  name: "Marcelo Borges"
  linkedin: "https://www.linkedin.com/in/marcelomborges/"

# If this is a project site, set your repo here
# url: "https://marceloborges.github.io"
# baseurl: "/borgescloud"
